version: "3.9"
services:
  dev:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5566:5566
    volumes:
      - /usr/src/app/build
      - /usr/src/app/coverage
      - /usr/src/app/node_modules
      - .:/usr/src/app
